### ISSUE TITLE
Exception during encoding of codicefiscale

### ISSUE THREAD

**Issue by aemmeemme** [LucaCappelletti94/random_italian_person#4]
When generating a random anagrafica, often i come across an exception related to the encoding of the codicefiscale.
The error is due to the date of birth. It falls off the validation date of the used municipality. Below there is the stacktrace error and the corresponding snippet of the municipalities.json file used by codicefiscale.py

In the use-case below we can see that the person's place of birth is Masainas and the date of birth is 1944-10-15.
But, if we search for Masainas in municipalities.json we can see that the 1944-10-15 is before the first valid date associated with this municipality.

I've avoided the exception by using a workaround in my code.
I've also collected some data. 

On 1m generated items, I got: 
- 57484 times I came across an error, 
- 3026 times I needed a second try, 
- 157 times a third try,
- 11 times a fourth try.

Stacktrace:
> Traceback (most recent call last):
>   File "####\ex.py", line 11, in <module>
>     person = RandomItalianPerson()
>   File "####\Python\Python39\lib\site-packages\random_italian_person\random_italian_person.py", line 73, in __init__
>     self._data["codice_fiscale"] = codicefiscale.encode(
>   File "####\Python\Python39\lib\site-packages\codicefiscale\codicefiscale.py", line 402, in encode
>     birthplace_code = encode_birthplace(birthplace, birthdate)
>   File "####\Python\Python39\lib\site-packages\codicefiscale\codicefiscale.py", line 337, in encode_birthplace
>     raise ValueError(
> ValueError: [codicefiscale] 'birthplace' / 'birthdate' arguments ('Masainas' / '1944-10-15') not mapped to code

municipalities.json

> {
>         "active": false,
>         "code": "M270",
>         "date_created": "1974-08-02T00:00:00",
>         "date_deleted": "2005-12-31T00:00:00",
>         "name": "Masainas",
>         "name_alt": "",
>         "name_alt_trans": "",
>         "name_slugs": [
>             "masainas"
>         ],
>         "name_trans": "Masainas",
>         "province": "CA"
>     },
>     {
>         "active": false,
>         "code": "M270",
>         "date_created": "2006-01-01T00:00:00",
>         "date_deleted": "2016-04-27T00:00:00",
>         "name": "Masainas",
>         "name_alt": "",
>         "name_alt_trans": "",
>         "name_slugs": [
>             "masainas"
>         ],
>         "name_trans": "Masainas",
>         "province": "CI"
>     },
>     {
>         "active": true,
>         "code": "M270",
>         "date_created": "2016-04-28T00:00:00",
>         "date_deleted": "",
>         "name": "Masainas",
>         "name_alt": "",
>         "name_alt_trans": "",
>         "name_slugs": [
>             "masainas"
>         ],
>         "name_trans": "Masainas",
>         "province": "SU"
>     },

Code snippet of the workaround

> while not person:
>         try:
>             person = RandomItalianPerson()
>         except:
>             pass

**Comment by LucaCappelletti94** [comment]
I'll integrate it, thank you.

**Comment by aemmeemme** [comment]
Ciao Luca.
Ho notato anche un'altra cosa, utilizzando la lib.
Alcuni paesi (mi è sembrato fossero i capoluoghi, principalmente) non hanno
un cap associato. Questo perché, una volta, avevano un cap generico che ora
è stato dismesso (infatti, utilizzando quel cap, i sistemi sui quali sto
effettuando dei test restituiscono errore). Attualmente, località simili,
risultano avere un intervallo di cap validi. Trattandosi di un generatore
random di anagrafiche, potrebbe essere utile inserire come cap associato il
primo dell'intervallo? Così facendo ad ogni località verrà associato un cap
valido (anche se si perderà la granularità sulle possibili varianti del cap
differente all'interno della stessa città).

Grazie mille e complimenti per il lavoro!

**Comment by LucaCappelletti94** [comment]
Non credo di avere capito esattamente la natura del problema, ti chiederei di aprire una issue separata dettagliando e facendo esempi su cosa ti aspetteresti. Considera che non sto più utilizzando questa libreria per lavoro, per cui per quanto cerco sempre di fare manutenzione non credo che avrò il tempo di aggiungere nuove features.

**Comment by aemmeemme** [comment]
ok no problem! 
Vedo di aprire una feature a parte, grazie!

Comunque, se possibile, posso fare il fork del progetto e farla io stesso la modifica, una volta concordata!

Grazie ancora!

**Comment by LucaCappelletti94** [comment]
Pull request sempre benvenute
